server:
  port: 8081
#spring.mvc.static-path-pattern=/** # Path pattern used for static resources.
spring:
    mvc:
    
    
      static-path-pattern: /**
    datasource:
        name: 本地
        url: jdbc:mysql://192.168.0.103:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: 168168
        # druid
#        type: com.alibaba.druid.pool.DruidDataSource
       
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      cache: false #暂时关闭
   



mybatis:
  mapper-locations: classpath:mappers/*.xml

   

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#文件上传
cbs:
    imagesPath:
        file:/D:/img/

redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 10000





